# Generated by Django 5.0.6 on 2024-06-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('Documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellido', models.CharField(max_length=25)),
                ('Correo', models.CharField(max_length=15, unique=True)),
                ('Celular', models.CharField(max_length=15, unique=True)),
                ('cargo', models.ForeignKey(db_column='Codigo_C', on_delete=django.db.models.deletion.CASCADE, to='cargo.cargo')),
            ],
        ),
    ]
