# Generated by Django 5.0.6 on 2024-06-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0005_paquetes'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('codigo_R', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('fecha_de_entrada', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha_de_salida', models.DateTimeField()),
                ('subtotal', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='dtllhabitacion',
            fields=[
                ('Codigo_DH', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Cantidad', models.SmallIntegerField()),
                ('Precio', models.FloatField()),
                ('Codigo_H', models.ForeignKey(db_column='Codigo_H', on_delete=django.db.models.deletion.CASCADE, to='servicio.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='dtllpaquete',
            fields=[
                ('Codigo_DPA', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Cantidad', models.SmallIntegerField()),
                ('Precio', models.FloatField()),
                ('Codigo_Pa', models.ForeignKey(db_column='Codigo_Pa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.paquetes')),
            ],
        ),
        migrations.CreateModel(
            name='dtllservicio',
            fields=[
                ('Codigo_DS', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Cantidad', models.SmallIntegerField()),
                ('Precio', models.IntegerField()),
                ('Codigo_S', models.ForeignKey(db_column='odigo_S', on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
    ]
