# Generated by Django 5.0.6 on 2024-06-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudad', '0001_initial'),
        ('cliente', '0001_initial'),
        ('empresa', '0001_initial'),
        ('reservar', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='Documento',
            field=models.ForeignKey(db_column='Documento', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Documento_C',
            field=models.ForeignKey(db_column='Documento_C', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Nit',
            field=models.ForeignKey(db_column='Nit', on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_PC',
            field=models.ForeignKey(db_column='codigo_PC', on_delete=django.db.models.deletion.CASCADE, to='ciudad.ciudad'),
        ),
        migrations.AddField(
            model_name='dtllservicio',
            name='Codigo_R',
            field=models.ForeignKey(db_column='Codigo_R', on_delete=django.db.models.deletion.CASCADE, to='reservar.reserva'),
        ),
        migrations.AddField(
            model_name='dtllpaquete',
            name='Codigo_R',
            field=models.ForeignKey(db_column='Codigo_R', on_delete=django.db.models.deletion.CASCADE, to='reservar.reserva'),
        ),
        migrations.AddField(
            model_name='dtllhabitacion',
            name='Codigo_R',
            field=models.ForeignKey(db_column='Codigo_R', on_delete=django.db.models.deletion.CASCADE, to='reservar.reserva'),
        ),
    ]
