# Generated by Django 5.0.6 on 2024-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('Codigo_f', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField()),
                ('Subtotal', models.FloatField()),
                ('iva', models.FloatField()),
                ('Total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Forma_P',
            fields=[
                ('Codigo_FP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=25)),
            ],
        ),
    ]
