# Generated by Django 5.0.6 on 2024-06-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('Codigo_H', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=1)),
                ('Precio', models.FloatField()),
                ('Estado', models.CharField(max_length=20)),
                ('Posicion', models.TextField()),
                ('Piso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('Codigo_Pa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Destinatario', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=25)),
                ('Fecha', models.DateTimeField()),
            ],
        ),
    ]
