# Generated by Django 5.0.6 on 2024-06-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_habitacion_paquete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='habitacion',
        ),
        migrations.DeleteModel(
            name='paquete',
        ),
    ]
