# Generated by Django 5.0.6 on 2024-06-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_delete_habitacion_delete_paquete'),
    ]

    operations = [
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('Codigo_H', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=1)),
                ('Precio', models.FloatField()),
                ('Estado', models.CharField(max_length=20)),
                ('Posicion', models.TextField()),
                ('Piso', models.CharField(max_length=20)),
            ],
        ),
    ]
