# Generated by Django 5.0.6 on 2024-06-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('Nit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('slogan', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=30)),
                ('descripcion', models.TextField()),
                ('codigo_PC', models.ForeignKey(db_column='codigo_PC', on_delete=django.db.models.deletion.CASCADE, to='ciudad.ciudad')),
            ],
        ),
    ]
